### PR TITLE
deps: Update various dependencies

### PR DESCRIPTION
**Pull request by CosmicHorrorDev**

### CODE REVIEW

**Comment by chenrui333** [comment]
@CosmicHorrorDev can you make a new release per this PR merge?

**Comment by chenrui333** [comment]
looks like this has been done off the code, hmm

image

**Comment by CosmicHorrorDev** [comment]
Yup yup. It was handled in #357 on the `v0.4` branch (although I don't love long lived branches like this, but `main` has breaking changes). Let me know if there's anything that needs fixing on the v0.4 series and I can make another point release as needed

**Comment by chenrui333** [comment]
it works for me (as long as there is some tag commit containing the patch, just look a bit weird :))

**Comment by CosmicHorrorDev** [comment]
Happy to hear it! Thanks for being a packager :heart:

**Comment by CosmicHorrorDev** [comment]
And the tag for it should be `v0.4.3`

**Pull request merged**
