### PR TITLE
Fix: Updating window title if new file loaded

### PR DESCRIPTION
**Pull request by BoolPurist**
Fixes the following [issue](https://github.com/Inlyne-Project/inlyne/issues/360)

Refactors: Encapsulated updating file watcher and window title into one function

Note: This was a regression bug.
In previous versions, this bug did not exit
See the following commit "a6bb495" with version 0.4.1

## Reason why PR on branch v0.4

The current version on crates.io seems to use commit 588687e8eccb2f01573dc5eed7597b62d7253ae4 on this branch.
Therefore, the addressed bug comes up when installing inlyne via the following command 

```txt
cargo install inlyne
```

It also seems that the most recent changes are done on this branch.

### CODE REVIEW

**Comment by CosmicHorrorDev** [comment]
Would you mind switching the base branch to `main`? v0.4 only exists for backporting fixes and won't be used after the pending 0.5.0 release

**Comment by CosmicHorrorDev** [comment]
Well that button didn't do what I wanted. I'll work on fixing the conflicts

**Comment by CosmicHorrorDev** [comment]
Ahhhh. I somehow forgot that this was already working as intended on main with

- #274

so this would strictly be for the `v0.4` branch :sweat_smile:. I could merge this as a backport, but I'm not sure if it's worth it or not since it'll also be fixed once 0.5.0 is released

**Comment by BoolPurist** [comment]
I think this path is then obsolete in that case. No biggie. Say the word and I close this PR.

**Comment by CosmicHorrorDev** [comment]
Fair enough. I'm sorry that I didn't realize earlier, thanks for your contribution nonetheless

**Pull request closed without merging**
